
find_path(LIBSNDFILE_INCLUDE_DIR sndfile.h)

set(LIBSNDFILE_INCLUDE_DIRS ${LIBSNDFILE_INCLUDE_DIR})

find_library(LIBSNDFILE_LIBRARY sndfile)
if (LIBSNDFILE_LIBRARY)
	set(LIBSNDFILE_LIBRARIES ${LIBSNDFILE_LIBRARY})
endif (LIBSNDFILE_LIBRARY)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LibSndFile DEFAULT_MSG LIBSNDFILE_INCLUDE_DIRS LIBSNDFILE_LIBRARIES)

